version: '3.2'

services:
  postgres-docker-container:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=booking123
      - POSTGRES_DB=room-booking
      - POSTGRES_USER=booking
    ports:
      - 5432:5432
  spring-room-booking-app:
    image: spring-room-booking-image
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres-docker-container
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=postgres-docker-container
      - DATABASE_USER=booking
      - DATABASE_PASSWORD=booking123
      - DATABASE_NAME=room-booking
      - DATABASE_PORT=5432
